### PR TITLE
Revert to old symbol resolution technique:

### LINKED ISSUE #134: t/runtime-bareword-filehandles.t fails (sometimes) on 5.16.3
So far, this is the only failure for Linux

http://www.cpantesters.org/cpan/report/085d336a-8b0b-11ec-9950-498f1f24ea8f

```
# Failed test 'Successfully handled bareword filehandles during runtime'
# at t/runtime-bareword-filehandles.t line 26.

# Failed test 'No observed error'
# at t/runtime-bareword-filehandles.t line 30.
# +-----------------------------------------------------------+----+-------+
# | GOT                                                       | OP | CHECK |
# +-----------------------------------------------------------+----+-------+
# | Can't use string ("DIR") as a symbol ref while "strict re | eq |       |
# | fs" in use at /usr/share/perl5/File/Find.pm line 719.\n   |    |       |
# +-----------------------------------------------------------+----+-------+
# Seeded srand with seed '20220210' from local date.
t/runtime-bareword-filehandles.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 
```

### PR DESCRIPTION
**Pull request by xsawyerx**
There's still a failing test which I cannot replicate. I'm hoping using a more bare-bones method will take care of this and to not actually debug why it's happening there.

I'm hoping this resolves #134.

### CODE REVIEW

File: lib/Test/MockFile.pm [hunk 1]
```diff
@@ -186,11 +186,12 @@ sub _upgrade_barewords {
...
     {
         no strict 'refs';
-        $handle = Symbol::qualify_to_ref( $args[1], caller(1) );
+        my $caller_pkg = caller(1);
+        $handle = *{"$caller_pkg\::$args[1]"};
     }
 
     # Check that the upgrading worked
-    ref $handle eq 'GLOB'
+    ref \$handle eq 'GLOB'
```
Comment (toddr) [inline lib/Test/MockFile.pm:194]: wouldn't this be a ref to a ref?

Comment (xsawyerx) [reply lib/Test/MockFile.pm:194]: Here's the weird part:

* If you keep it `ref $handle eq 'GLOB'` with the bare-bones technique (which we revert to here), you will replicate the error (the test will fail)
* If you change it to `ref \$handle eq 'GLOB'` with the `Symbol.pm` technique, that also replicates the error (the test will fail)

In other words:

```
Symbol.pm + ref \$handle = crash
*{caller::...} + ref $handle = crash

Symbol.pm + ref $handle = no crash (except the test failure we're trying to fix now)
*{caller::...} + ref $handle = no crash (and maybe not the test failure we're trying to fix soon?)
```
